#Struktogrammeditor Properties
#Mon Dec 16 14:44:00 MSK 2024
cespacesperstep=3
mousewheelresize=0
celanguage=0
caption9=\u00F8
caption8=Aufruf
pathfiles=C\:\\GitHub\\OAiP\\\u041B\u0430\u0431\u04307\\Laba7.Main
caption7=Aussprung
caption6=Endlosschleife
caption5=Do-While Schleife
caption4=While Schleife
useantialiasing=0
caption3=0 < i < anzahl
captionstyle=1
stretchlast=0
caption2=Fallauswahl
caption1=Verzweigung
caption0=Anweisung
lookandfeel=0
useelementshortcuts=1
pathpictures=
zoomy=10
zoomx=10
cespaces=3
cecomments=1
